[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ta-config"
version = "0.1.0"
description = "A high-performance quantitative framework featuring decoupled vectorized and low-latency O(1) streaming technical indicators."
readme = "README.md"

license = {file = "LICENSE"}
requires-python = ">=3.12.10"
dependencies = [
    "pandas>=2.3.2",
    "numpy>=2.2.6",
    "pydantic>=2.0"
]

[project.optional-dependencies]
test = [
    "pytest>=9.0.2",
    "pytest-mock"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "9.0.2"
addopts = "-ra -q"
testpaths = [
    "tests"
]
pythonpath = ["src"]
markers = [
    "unit: Core isolated unit tests using mocks.",
    "integration: Tests that interact with the live Windows OS or network dependencies."
]